### ISSUE TITLE
Additivity check failed in TreeExplainer!

### ISSUE THREAD

**Issue by avinashbarnwal** [ing-bank/probatus#102]
**Describe the bug**

Thanks for creating this package. I am trying to use ShapRFE with lightGBM learner and found the below error.

Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was -1.387365, while the model output was -1.209384.

**To Reproduce**
I can't reproduce it as the data is private.

**Expected behavior**
I expected it to run as a normal process.

**Desktop (please complete the following information):**
 - probatus version [e.g. 1.5.0]
 - Linux

How to resolve this error?

**Comment by Matgrb** [comment]
Thanks for making this issue, we have recently experienced this bug as well.
It is related to SHAP package, and i suppose that they haven't found a way to fix it on their side. 
https://github.com/slundberg/shap/issues/1071
https://github.com/slundberg/shap/issues/930

There are a couple of solutions that we can apply to mitigate it for now:
- try a different tree-based model, since SHAP is having this issue mainly with XGBoost and LightGBM. Definitely worth trying out
- use `check_additivity=False` option for now, until this issue is fixed. This option disables the check. I will make sure that this option is also available in the next version of probatus. We will hopefully make this change today and right after that make a release. I will keep you posted.

**Comment by Matgrb** [comment]
The `check_additivity` modification is not available in probatus 1.7.0.

try this and let me know if this solves the issue for now:
```
fit_compute(X, y, check_additivity=False)
```
or
```
fit(X, y, check_additivity=False)
```

**Comment by avinashbarnwal** [comment]
In what version we have check_additivity modification. Do I need to upgrade the package to use this feature?

**Comment by Matgrb** [comment]
You need to upgrade probatus to 1.7.0
```
pip install probatus==1.7.0
```

Let us know if it works.

**Comment by timvink** [comment]
> The `check_additivity` modification is not available in probatus 1.7.0.

You meant 'now' right ;)

**Comment by Matgrb** [comment]
Indeed, sorry for the misleading typo. I corrected it in the above comment

**Comment by avinashbarnwal** [comment]
This Worked.
