### ISSUE TITLE
VarianceThresholdSelector

### ISSUE THREAD

**Issue by orchardbirds** [ing-bank/probatus#130]
Not sure this is probatus-appropriate, but let me know @Matgrb 

I already have the code for it.

**Problem Description**
The variance threshold from scikitlearn is great, but if we want to keep a pandas df, it require tweaking

**Desired Outcome**
```python
VTS = VarianceThresholdSelector(threshold=0.0)
df = VTS.fit_transform(df)
```

**Comment by Matgrb** [comment]
We have discussed this one in #122 . 
I think for now it is better to not add it to probatus, because of, large workload to add it, and low value added compared to sklearn.
Maybe it also fits better into sklego or some other package that implements sklearn transformers, i suggest making an issue about it there.
