### ISSUE TITLE
Does this Library Support Regression and/or Multiclass Classification

### ISSUE THREAD

**Issue by CMobley7** [ing-bank/probatus#166]
To Whom It May Concern,

I found Probatus via the following article, https://medium.com/ing-blog/open-sourcing-shaprfecv-improved-feature-selection-powered-by-shap-994fe7861560, when looking for a way to do RFE with SHAP values on tree-based models. However, I’m attempting to solve both regression and multiclass classification problems. After looking at the documentation, this library appears to only support binary classification. Am I reading the documentation correctly? If so, is this feature on the roadmap?

Thank you for your time and attention to this matter. I hope that this question finds you well and that you have a great rest of the week. God bless.

Very Respectfully,
CMobley7

**Comment by christophermadsen** [comment]
`Probatus` will work for both regression and classification.

The `probatus` docs do recommend using `LightGBM` or `XGBoost`, so I don't know if all tree-based regression models will work, but conceptually any `sklearn`-like model should work. You can have a look at the models being tested in the [tests](https://github.com/ing-bank/probatus/blob/main/tests/feature_elimination/test_feature_elimination.py).

I have personally run experiments with the LGBMRegressor without any issues on several occassions.

The docs aren't outdated, but there are currently only tests for binary classification.

**Comment by CMobley7** [comment]
@christophermadsen ,

Thank you for your quick and thorough response. I really appreciate it. I planned on using either `XGBoost` or `LightGBM`; so that works out perfectly.

Thanks again. Have a great rest of the week. God bless.

Very Respectfully,
CMobley7

**Comment by Matgrb** [comment]
The idea is we provide full support for binary classifiers for all features. Some features might work with multiclass or regression, especially ShapRFECV, and if they don't please do make an issue. It would be cool to actually add some unit tests for regressors and multiclass to that module, since is is most used one in the package. I made this issue to outline what needs to be done#169 

However, some of the features e.g.  ShapModelInterpreter will not work with regression as they are right now, due to the fact that the feature measures AUC performance by default. In case there is interest in making other features work, please make an issue, and we see how this can be done.
