### ISSUE TITLE
SHAPREFCV provides optimistic results for validation

### ISSUE THREAD

**Issue by anilkumarpanda** [ing-bank/probatus#70]
**Describe the bug**
SHAPRFECV provides an optimistic results for the validation metrics while eliminating features from a random dataset.

**To Reproduce**
Code or steps to reproduce the error
```python

def make_data(N=1000, n_vars=10,
              n_classes=2):
    X = np.random.normal(size=(N,n_vars))
    y = np.random.choice(n_classes, N)
    
    return X, y

X,y = make_data(N=10000,n_vars=50)

X = pd.DataFrame(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the model:
clf = lightgbm.LGBMClassifier(n_estimators=10, num_leaves=7)

# Run RFECV and ShapRFECV with the same parameters
rfe = RFECV(clf, step=1, cv=20, scoring='roc_auc', n_jobs=3).fit(X_train, y_train)
shap_elimination = ShapRFECV(clf=clf, step=1, cv=20, scoring='roc_auc', n_jobs=3)
shap_report = shap_elimination.fit_compute(X_train, y_train)

# Compare the CV Validation AUC for different number of features in each method.
ax = pd.DataFrame({'RFECV Validation AUC': list(reversed(rfe.grid_scores_)),
                   'ShapRFECV Validation AUC': shap_report['val_metric_mean'].values.tolist()}, 
                 index=shap_report['num_features'].values.tolist()).plot(ylim=(0.4,0.7), rot=10, title='Comparison of RFECV and ShapRFECV', figsize=(10,5))
ax.set_ylabel("Model Performance")
ax.set_xlabel("Number of features")
ax.invert_xaxis()
plt.axhline(y=0.5,linestyle='--',color='r')
plt.show()


```
![image](https://user-images.githubusercontent.com/7496719/107666045-5c063a80-6c8e-11eb-9d4d-b260b5b8ae58.png)

```python
# For simple model.
clf = LogisticRegression()

```
![image](https://user-images.githubusercontent.com/7496719/107666845-3d547380-6c8f-11eb-83b1-0489d2f99671.png)

**Expected behavior**
Incase of a random dataset,  the calculated metrics should be as close to 0.5 as possible. 

**Desktop (please complete the following information):**
 - probatus version [e.g. 1.5.0]
 - OS: MacOS

**Comment by Matgrb** [comment]
The occurrence of the issue you mention could be due to multiple reasons:
- Performing hyperparameter optimization - in your case you do not apply it, but it is natural that it would increase the validation AUC, due to multiple runs for different parameters.
- Even in the randomly created dataset, there could be some features that have predictive power by random, especially for a small sample of 1000. If that is the case above, then it is not a bug and ShapRFECV exploits this better than RFECV because of using SHAP as a proxy for feature importance. 

I repeated the test with Lgbm for a larger sample of 10k:
![image](https://user-images.githubusercontent.com/40659437/108052561-9d129c00-704c-11eb-9f62-40eed9c19f70.png)

and 50k:
![image](https://user-images.githubusercontent.com/40659437/108052759-dfd47400-704c-11eb-83a0-addd0b663794.png)

I think the deviation from 0.5 AUC becomes very marginal, and appears due to some of the random variables having by random some predictive power. The more data we use, the less and later in the process it appears.

I would say this is not a bug. What do you think?

**Comment by anilkumarpanda** [comment]
Yes, that is my observation as well.  For small no.of features and no.of rows the results are always optimistic as compared to the RFECV. Though, this is *feature* I think we should mention it some where in the docs in the form of a warning or a disclaimer.

`We have observed that in case of smaller dataset n_rows< 5k ,  n_cols<10 the the validation results can be marginally optimistic since it depends on the underlying SHAP values and the trained model.`

Since dealing with random data a validation roc of 0.52 and 0.5 may not matter much, however depending on the use case a difference of 0.01-0.02 can be huge.
What do you think ?

**Comment by Matgrb** [comment]
I wouldn't consider it as optimistic in that case. If you have randomly generated features, especially for small datasets, some of the features will have some predictive power by random. The fact that you randomly generated the data does not guarantee that there is no predictive power in them. Only when the sample becomes large, this becomes highly probable. I would also argue if you have a very small sample <1k, and a lot of random features >100, the AUC can be even higher, because we increase the number of features that by random could have predictive power.

The fact that AUC is different from 0.5 comes from the predictive power of these features and the fact that ShapRFECV uses more efficient proxy for selecting these features over others. ShapRFECV removes noisy features and prevents overfitting of the model on the fully random features. RFECV uses impurity metrics, which is known to be biased towards high cardinality features, which is the case for randomly generated values. Therefore, the other proxy is less effective for this use case. There are no other major differences between these two approaches in the provided code example.

In my view, the observation provides proof that if there is even marginal predictive power in the features ShapRFECV manages to extract it more efficiently than RFECV. It is not optimistic, because in both cases we use 20-fold cross validation to prove that in fact the validation AUC is higher than 50%.

**Comment by Matgrb** [comment]
[This experiment ](https://scikit-learn.org/stable/auto_examples/inspection/plot_permutation_importance.html#sphx-glr-auto-examples-inspection-plot-permutation-importance-py) explains how impurity metrics are fooled by random variables. The random variables could have a very high importance even if there is completely no predictive power in them. That is why the RFECV does not manage to get a boost in AUC,  as we observe in ShapRFECV

**Comment by anilkumarpanda** [comment]
Yes, the random variables generated do have very low correlation and SHAP is able to pick that and maybe that is why the slight boost in performance.Thanks for investigating this. I will close the issue.
