### ISSUE TITLE
BorutaShap

### ISSUE THREAD

**Issue by rspadim** [ing-bank/probatus#83]
Could be possible the use of borutashap?

https://pypi.org/project/BorutaShap/

**Comment by timvink** [comment]
Hi @rspadim. `BorutaShap` looks like an interesting approach to feature selection. `probatus` offers `ShapRFECV` as a feature selector, with a slightly different API. I image a `BorutaShapRFECV` could be added to the `BorutaShap` package, but I don't immediately see where/how `BorutaShap` could integrate with `probatus`. Did you already have anything specific in mind that you can share?

**Comment by rspadim** [comment]
not yet, maybe talking with borutashap folks, will check it

**Comment by Matgrb** [comment]
@rspadim in probatus we would like to limit the number of dependencies, and i am afraid that building similar feature for `Boruta` or `BorutaShap` will cause going the other direction. Right now with `SHAP` only, we have experience a lot of extra maintenance workload.
Moreover, I think `BorutaSHAP` on its own is a package that performs feature selection, so I think it is best to make an issue there and suggest what extra features could fit in there. Since they already specialize in feature selection, using both Boruta and SHAP, maybe they can benefit from the ideas we had in `ShapRFECV`.
What do you think?

For now I will close the issue, just to keep the issue board clean. But in the future if we see this as a possibility, we can reopen it.
